[platformio]
default_envs =
    m5stack-basic-dccex

[env:esp32dev-dccex]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson @ ^7.2.1
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer

build_src_filter =
    +<*>
    -<Z21CommandCenter.cpp>
    -<CommandCenterManager.cpp>
    -<CommandCenterFactory.cpp>

build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D HUB_USE_DISPLAY=0
    -D HUB_TARGET_ESP32_DEVKIT=1
    -D HUB_CC_DCCEX=1


[env:esp32dev-z21]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson @ ^7.2.1
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer

build_src_filter =
    +<*>
    -<DccExBridge.cpp>
    -<CommandCenterManager.cpp>
    -<CommandCenterFactory.cpp>

build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D HUB_USE_DISPLAY=0
    -D HUB_TARGET_ESP32_DEVKIT=1
    -D HUB_CC_Z21=1


[env:m5stack-basic-dccex]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson @ ^7.2.1
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer

build_src_filter =
    +<*>
    -<Z21CommandCenter.cpp>
    -<CommandCenterManager.cpp>
    -<CommandCenterFactory.cpp>

build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D HUB_USE_DISPLAY=1
    -D HUB_DISPLAY_M5STACK_BASIC=1
    -D HUB_TARGET_M5STACK_BASIC=1
    -D HUB_CC_DCCEX=1


[env:m5stack-basic-z21]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson @ ^7.2.1
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer

build_src_filter =
    +<*>
    -<DccExBridge.cpp>
    -<CommandCenterManager.cpp>
    -<CommandCenterFactory.cpp>

build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D HUB_USE_DISPLAY=1
    -D HUB_DISPLAY_M5STACK_BASIC=1
    -D HUB_TARGET_M5STACK_BASIC=1
    -D HUB_CC_Z21=1


[env:cyd-2432s028-dccex]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson @ ^7.2.1
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
    adafruit/Adafruit GFX Library @ ^1.12.1
    adafruit/Adafruit ILI9341 @ ^1.6.2

build_src_filter =
    +<*>
    -<Z21CommandCenter.cpp>
    -<CommandCenterManager.cpp>
    -<CommandCenterFactory.cpp>

build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D HUB_USE_DISPLAY=1
    -D HUB_DISPLAY_CYD_2432S028=1
    -D HUB_TARGET_CYD_2432S028=1
    -D HUB_CC_DCCEX=1


[env:cyd-2432s028-z21]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson @ ^7.2.1
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
    adafruit/Adafruit GFX Library @ ^1.12.1
    adafruit/Adafruit ILI9341 @ ^1.6.2

build_src_filter =
    +<*>
    -<DccExBridge.cpp>
    -<CommandCenterManager.cpp>
    -<CommandCenterFactory.cpp>

build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D HUB_USE_DISPLAY=1
    -D HUB_DISPLAY_CYD_2432S028=1
    -D HUB_TARGET_CYD_2432S028=1
    -D HUB_CC_Z21=1
