[platformio]
default_envs =
    m5stack-basic-dccex

[env:esp32dev-dccex]
platform = espressif32 @ 6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson @ ^7.2.1
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer

build_src_filter =
    +<*>
    -<Z21CommandCenter.cpp>
    -<CommandCenterManager.cpp>
    -<CommandCenterFactory.cpp>

build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D HUB_USE_DISPLAY=0
    -D HUB_TARGET_ESP32_DEVKIT=1
    -D HUB_CC_DCCEX=1


[env:esp32dev-z21]
platform = espressif32 @ 6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson @ ^7.2.1
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer

build_src_filter =
    +<*>
    -<DccExBridge.cpp>
    -<CommandCenterManager.cpp>
    -<CommandCenterFactory.cpp>

build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D HUB_USE_DISPLAY=0
    -D HUB_TARGET_ESP32_DEVKIT=1
    -D HUB_CC_Z21=1


[env:m5stack-basic-dccex]
platform = espressif32 @ 6.12.0
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson @ ^7.2.1
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer

build_src_filter =
    +<*>
    -<Z21CommandCenter.cpp>
    -<CommandCenterManager.cpp>
    -<CommandCenterFactory.cpp>

build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D HUB_USE_DISPLAY=1
    -D HUB_DISPLAY_M5STACK_BASIC=1
    -D HUB_TARGET_M5STACK_BASIC=1
    -D HUB_CC_DCCEX=1


[env:m5stack-basic-z21]
platform = espressif32 @ 6.12.0
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson @ ^7.2.1
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer

build_src_filter =
    +<*>
    -<DccExBridge.cpp>
    -<CommandCenterManager.cpp>
    -<CommandCenterFactory.cpp>

build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D HUB_USE_DISPLAY=1
    -D HUB_DISPLAY_M5STACK_BASIC=1
    -D HUB_TARGET_M5STACK_BASIC=1
    -D HUB_CC_Z21=1


[env:waveshare-s3-lcd7-dccex]
platform = espressif32 @ 6.12.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi

debug_tool = esp-builtin
debug_init_break = tbreak setup

lib_deps =
    bblanchon/ArduinoJson @ ^7.2.1
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
    https://github.com/lovyan03/LovyanGFX.git#fb7cec222726b92676e26126246d59f70f04ced2

build_src_filter =
    +<*>
    -<Z21CommandCenter.cpp>
    -<CommandCenterManager.cpp>
    -<CommandCenterFactory.cpp>

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D HUB_USE_DISPLAY=1
    -D HUB_DISPLAY_WAVESHARE_S3_LCD7=1
    -D HUB_TARGET_WAVESHARE_S3_LCD7=1
    -D HUB_CC_DCCEX=1
    -D S88_I2C_ENABLED=0
