#!/usr/bin/env bash
set -Eeuo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="${REPO_ROOT}/desktop/DCCExpressHub.Net"
ENV_FILE="${BACKEND_DIR}/.env.linux"
PROJECT="${BACKEND_DIR}/DCCExpressHub.Net.csproj"

DEFAULT_HTTP_URL="http://0.0.0.0:5174"

die() {
    echo "ERROR: $*" >&2
    exit 1
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

prompt() {
    local label="$1"
    local default_value="${2-}"
    local value=""

    if [[ -n "$default_value" ]]; then
        read -r -p "$label [$default_value]: " value
        printf '%s' "${value:-$default_value}"
    else
        read -r -p "$label: " value
        printf '%s' "$value"
    fi
}

write_env_value() {
    local key="$1"
    local value="$2"
    printf 'export %s=%q\n' "$key" "$value"
}

save_common_env() {
    local http_url="$1"

    {
        echo "# Generated by run-linux.sh"
        echo "# Local machine configuration; ignored by Git."
        write_env_value "DCCEXPRESS_HTTP_URL" "$http_url"
        write_env_value "DCCEXPRESS_CONTENT_ROOT" "$BACKEND_DIR"
        write_env_value "DCCEXPRESS_WEB_ROOT" "$BACKEND_DIR/wwwroot"
    } > "$ENV_FILE"
}

append_env() {
    local key="$1"
    local value="$2"
    write_env_value "$key" "$value" >> "$ENV_FILE"
}

configure_yamorc() {
    local host
    local z21_port
    local lb_port
    local binary_port
    local sensor_offset
    local binary_feedback

    host="$(prompt "YaMoRC IP / hostname" "192.168.1.123")"
    z21_port="$(prompt "Z21 UDP port" "21105")"
    lb_port="$(prompt "LocoNet LBServer TCP port" "1234")"
    binary_port="$(prompt "LocoNet binary TCP port" "5560")"
    sensor_offset="$(prompt "LocoNet sensor offset" "0")"

    read -r -p "Enable LocoNet binary feedback? [y/N]: " binary_feedback
    binary_feedback="${binary_feedback,,}"

    append_env "CommandCenter__Protocol" "yamorc7010"
    append_env "Z21__Host" "$host"
    append_env "Z21__Port" "$z21_port"

    append_env "LocoNet__Host" "$host"
    append_env "LocoNet__LbServerPort" "$lb_port"
    append_env "LocoNet__LbServerFeedback" "true"
    append_env "LocoNet__BinaryPort" "$binary_port"

    if [[ "$binary_feedback" == "y" || "$binary_feedback" == "yes" ]]; then
        append_env "LocoNet__BinaryFeedback" "true"
    else
        append_env "LocoNet__BinaryFeedback" "false"
    fi

    append_env "LocoNet__SensorOffset" "$sensor_offset"
}

configure_z21() {
    local host
    local port

    host="$(prompt "Z21 IP / hostname" "192.168.1.111")"
    port="$(prompt "Z21 UDP port" "21105")"

    append_env "CommandCenter__Protocol" "z21"
    append_env "Z21__Host" "$host"
    append_env "Z21__Port" "$port"
}

configure_dccex_tcp() {
    local host
    local port

    host="$(prompt "DCC-EX IP / hostname" "192.168.1.143")"
    port="$(prompt "DCC-EX TCP port" "2560")"

    append_env "CommandCenter__Protocol" "dccex"
    append_env "DccEx__Transport" "Tcp"
    append_env "DccEx__Host" "$host"
    append_env "DccEx__Port" "$port"
}

configure_dccex_serial() {
    local serial_port

    serial_port="$(prompt "DCC-EX serial device" "/dev/ttyACM0")"

    append_env "CommandCenter__Protocol" "dccex"
    append_env "DccEx__Transport" "Serial"
    append_env "DccEx__SerialPort" "$serial_port"

    if [[ ! -e "$serial_port" ]]; then
        echo
        echo "WARNING: serial device does not currently exist: $serial_port"
    elif [[ ! -r "$serial_port" || ! -w "$serial_port" ]]; then
        echo
        echo "WARNING: current user may not have serial access:"
        ls -l "$serial_port" || true
        echo
        echo "On Debian this usually means adding the user to dialout:"
        echo "  sudo usermod -aG dialout $USER"
        echo "then log out and back in."
    fi
}

configure() {
    local http_url
    local choice

    echo
    echo "DCCExpressHub Linux backend configuration"
    echo "========================================"
    echo "1) YaMoRC YD7010 (Z21 + separate LocoNet)"
    echo "2) Roco Z21"
    echo "3) DCC-EX TCP"
    echo "4) DCC-EX Serial"
    echo

    read -r -p "Command center [1-4]: " choice

    http_url="$(prompt "Backend listen URL" "$DEFAULT_HTTP_URL")"
    save_common_env "$http_url"

    case "$choice" in
        1)
            configure_yamorc
            ;;
        2)
            configure_z21
            ;;
        3)
            configure_dccex_tcp
            ;;
        4)
            configure_dccex_serial
            ;;
        *)
            rm -f "$ENV_FILE"
            die "Invalid command-center selection."
            ;;
    esac

    echo
    echo "Saved Linux backend configuration:"
    echo "  $ENV_FILE"
}

clear_backend_env() {
    unset CommandCenter__Protocol || true

    unset Z21__Host || true
    unset Z21__Port || true

    unset LocoNet__Host || true
    unset LocoNet__LbServerPort || true
    unset LocoNet__LbServerFeedback || true
    unset LocoNet__BinaryPort || true
    unset LocoNet__BinaryFeedback || true
    unset LocoNet__SensorOffset || true

    unset DccEx__Transport || true
    unset DccEx__Host || true
    unset DccEx__Port || true
    unset DccEx__SerialPort || true

    unset DCCEXPRESS_HTTP_URL || true
    unset DCCEXPRESS_CONTENT_ROOT || true
    unset DCCEXPRESS_WEB_ROOT || true
}

load_env() {
    [[ -f "$ENV_FILE" ]] || die "Missing $ENV_FILE"

    clear_backend_env

    # This file is generated locally by this script and contains only shell-
    # escaped export statements.
    # shellcheck disable=SC1090
    source "$ENV_FILE"
}

show_config() {
    echo
    echo "DCCExpressHub Linux backend"
    echo "==========================="
    echo "HTTP:            ${DCCEXPRESS_HTTP_URL:-$DEFAULT_HTTP_URL}"
    echo "Content root:    ${DCCEXPRESS_CONTENT_ROOT:-$BACKEND_DIR}"

    case "${CommandCenter__Protocol:-dccex}" in
        yamorc7010)
            echo "Command center:  YaMoRC YD7010"
            echo "Z21:             ${Z21__Host:-?}:${Z21__Port:-21105}"
            echo "LocoNet:         ${LocoNet__Host:-?}:${LocoNet__LbServerPort:-1234}"
            echo "Binary feedback: ${LocoNet__BinaryFeedback:-false}"
            echo "Sensor offset:   ${LocoNet__SensorOffset:-0}"
            ;;
        z21)
            echo "Command center:  Roco Z21"
            echo "Z21:             ${Z21__Host:-?}:${Z21__Port:-21105}"
            ;;
        *)
            if [[ "${DccEx__Transport:-Tcp}" == "Serial" ]]; then
                echo "Command center:  DCC-EX Serial"
                echo "Serial device:   ${DccEx__SerialPort:-?}"
                echo "Baud:            115200"
            else
                echo "Command center:  DCC-EX TCP"
                echo "DCC-EX:          ${DccEx__Host:-?}:${DccEx__Port:-2560}"
            fi
            ;;
    esac

    echo
}

usage() {
    cat <<'EOF'
Usage:
  ./run-linux.sh
  ./run-linux.sh --configure
  ./run-linux.sh --show
  ./run-linux.sh --build
  ./run-linux.sh --help

Default behavior:
  - if .env.linux does not exist, configure interactively
  - if it exists, reuse the saved configuration
  - launch DCCExpressHub.Net with dotnet run
EOF
}

main() {
    command_exists dotnet ||
        die ".NET SDK/runtime not found in PATH."

    case "${1-}" in
        --help|-h)
            usage
            exit 0
            ;;
        --configure)
            configure
            load_env
            show_config
            exec dotnet run --project "$PROJECT"
            ;;
        --show)
            load_env
            show_config
            exit 0
            ;;
        --build)
            cd "$BACKEND_DIR"
            exec dotnet build "$PROJECT"
            ;;
        "")
            ;;
        *)
            usage
            exit 2
            ;;
    esac

    if [[ ! -f "$ENV_FILE" ]]; then
        configure
    else
        echo "Using saved Linux configuration: $ENV_FILE"
        echo "Run with --configure to change it."
    fi

    load_env
    show_config

    cd "$BACKEND_DIR"
    exec dotnet run --project "$PROJECT"
}

main "$@"
